send_single_email_notification:
  path: /notifications/{notificationChannelId}/send
  methods: POST
  controller: Apps\Api\src\Controller\Notification\SendNotificationController

send_batch_email_notifications:
  path: /notifications/{notificationChannelId}/send/batch
  methods: POST
  controller: Apps\Api\src\Controller\Notification\SendBatchNotificationsController
