openapi: "3.0.0"
info:
  version: 0.0.2
  title: Notificator Api
servers:
  - url: http://localhost:8000/

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

